import os

DATABASE_URL = os.getenv("DATABASE_URL")
VALID_USER_NAME = os.getenv("USER_NAME", "admin") # TODO: WARNING! REMOVE THE DEFAULT VALUE IN PRODUCTION
VALID_PASSWORD = os.getenv("PASSWORD", "admin") # TODO: WARNING! REMOVE THE DEFAULT VALUE IN PRODUCTION
