apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-profile-audit
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user-profile-audit
  template:
    metadata:
      labels:
        app: user-profile-audit
    spec:
      containers:
      - name: user-profile-audit
        image: user-profile-audit:latest
        ports:
        - containerPort: 8000